"""Assemble the multiworld patch (mw/mw.asm) into world/smmr/data/mw.ips.

The defines come from world/smmr/data/abi.toml. asar patches a ROM image rather than producing a patch, so the
source is assembled onto two blank 4 MiB images, one of 00 and one of FF bytes: every byte that differs from its
blank in either image was written by the patch.

    python tools/build_mw.py           # ASAR=path/to/asar to use another assembler build
"""
from __future__ import annotations

import os
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "world" / "smmr"))   # `core` alone: importing `smmr` needs Archipelago

from core import ips  # noqa: E402
from core.abi import Abi  # noqa: E402

ASAR = Path(os.environ.get("ASAR", ROOT / "build/asar/asar/bin/asar"))
ROM_SIZE = 0x400000


def assemble(source: Path, fill: int, scratch: Path) -> bytes:
    rom = scratch / f"blank-{fill:02x}.sfc"
    rom.write_bytes(bytes([fill]) * ROM_SIZE)
    result = subprocess.run([str(ASAR), "--no-title-check", "--fix-checksum=off", str(source), str(rom)],
                            capture_output=True, text=True)
    if result.returncode != 0:
        sys.exit(f"asar failed:\n{result.stdout}{result.stderr}")
    return rom.read_bytes()


def main() -> None:
    abi = Abi.parse((ROOT / "world/smmr/data/abi.toml").read_text())
    build = ROOT / "mw" / "build"
    build.mkdir(exist_ok=True)
    (build / "abi.asm").write_text("; Generated by tools/build_mw.py from world/smmr/data/abi.toml\n" + abi.defines())

    with tempfile.TemporaryDirectory() as tmp:
        zeros = assemble(ROOT / "mw" / "mw.asm", 0x00, Path(tmp))
        ones = assemble(ROOT / "mw" / "mw.asm", 0xFF, Path(tmp))
    writes = {i: zeros[i] for i in range(ROM_SIZE) if zeros[i] != 0x00 or ones[i] != 0xFF}
    if any(zeros[i] != ones[i] for i in writes):
        sys.exit("the patch output depends on the ROM's contents (it reads the ROM it patches)")
    (ROOT / "world/smmr/data/mw.ips").write_bytes(ips.encode(writes))
    print(f"mw.ips: {len(writes)} bytes")


if __name__ == "__main__":
    main()
