"""
Prepare the MapRandomizer submodule for building: initialize the submodules that are needed, apply this
repository's patches to it (idempotently), fetch the Samus sprite manifest, and write the version files derived from
Map Rando's version (rust/VERSION) and this repository's WORLD_REVISION.

The world version is 0.<Map Rando version>.<world revision>, e.g. 0.123.0; the native module has the same version.

Usage: python tools/prepare_upstream.py
"""
import glob
import json
import os
import re
import subprocess
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MR = os.path.join(ROOT, "MapRandomizer")
WORLD = os.path.join(ROOT, "worlds", "sm_map_rando_upstream")
SPRITE_MANIFEST = os.path.join(MR, "MapRandoSprites", "samus_sprites", "manifest.json")


def git(*args, cwd=MR, check=True):
    return subprocess.run(["git", *args], cwd=cwd, check=check, capture_output=True, text=True)


def init_submodules():
    git("submodule", "update", "--init", "MapRandomizer", cwd=ROOT)
    git("submodule", "update", "--init", "--depth", "1", "sm-json-data", "rust/lznint", "asar")


def apply_patches():
    for patch in sorted(glob.glob(os.path.join(ROOT, "patches", "*.patch"))):
        if git("apply", "--reverse", "--check", patch, check=False).returncode == 0:
            print(f"Already applied: {os.path.basename(patch)}")
            continue
        result = git("apply", patch, check=False)
        if result.returncode != 0:
            raise SystemExit(f"Patch {os.path.basename(patch)} doesn't apply to the MapRandomizer submodule; update "
                             f"it for the new upstream version:\n{result.stderr}")
        print(f"Applied: {os.path.basename(patch)}")


def fetch_sprite_manifest():
    commit = git("ls-tree", "HEAD", "MapRandoSprites").stdout.split()[2]
    url = f"https://raw.githubusercontent.com/blkerby/MapRandoSprites/{commit}/samus_sprites/manifest.json"
    os.makedirs(os.path.dirname(SPRITE_MANIFEST), exist_ok=True)
    urllib.request.urlretrieve(url, SPRITE_MANIFEST)


def write_versions():
    map_rando_version = open(os.path.join(MR, "rust", "VERSION")).read().strip()
    revision = open(os.path.join(ROOT, "WORLD_REVISION")).read().strip()
    version = f"0.{map_rando_version}.{revision}"
    cargo = os.path.join(ROOT, "native", "pysmmaprando_upstream", "Cargo.toml")
    s = open(cargo).read()
    s = re.sub(r'(?m)^version = "[^"]*"', f'version = "{version}"', s, count=1)
    open(cargo, "w").write(s)
    with open(os.path.join(WORLD, "version.py"), "w") as f:
        f.write(f'# Generated by tools/prepare_upstream.py\nMAP_RANDO_VERSION = {int(map_rando_version)}\n'
                f'WORLD_VERSION = "{version}"\n')
    manifest_path = os.path.join(WORLD, "archipelago.json")
    manifest = json.load(open(manifest_path))
    manifest["world_version"] = version
    with open(manifest_path, "w") as f:
        json.dump(manifest, f, indent=4)
        f.write("\n")
    print(f"World version {version} (Map Rando v{map_rando_version})")


if __name__ == "__main__":
    init_submodules()
    apply_patches()
    fetch_sprite_manifest()
    write_versions()
